# –°–±–æ—Ä–∫–∞ (–∏ –ø—É–±–ª–∏–∫–∞—Ü–∏—è) –ø—Ä–æ–µ–∫—Ç–∞

name: AArkhipenko/user-service build (and publish)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: '–¢–∏–ø —Å–±–æ—Ä–∫–∏'
        required: true
        default: 'build'
        type: choice
        options:
        - build
        - release

jobs:
  call-main-pipeline:
    name: "üöÄ Call Main Pipeline"
    runs-on: ubuntu-latest
    steps:
      - name: Call main build workflow
        uses: AArkhipenko/pipelines/.github/workflows/dotnet@main
        with:
          dotnet_version: 7.0.x
          build_type: ${{ github.event.inputs.build_type }}
          branch_name: ${{ github.ref_name }}
          repository_name: ${{ github.repository }}
